# Generated by Django 5.0.9 on 2024-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('nro_documento', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id_detalle_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'DETALLE_DEVOLUCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=18)),
            ],
            options={
                'db_table': 'DETALLE_PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleReposicion',
            fields=[
                ('id_detalle_reposicion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'DETALLE_REPOSICION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion_motivo', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'DEVOLUCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaEntrega',
            fields=[
                ('id_ficha_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=25, null=True)),
            ],
            options={
                'db_table': 'FICHA_ENTREGA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'METODO_PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('monto_total', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reposicion',
            fields=[
                ('id_reposicion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion_motivo', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'REPOSICION',
                'managed': False,
            },
        ),
    ]
