# Generated by Django 5.0.9 on 2024-12-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CATEGORIA',
            },
        ),
        migrations.CreateModel(
            name='DetalleEgreso',
            fields=[
                ('id_detalle_egreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'DETALLE_EGRESO',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id_egreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('id_detalle_egreso', models.ForeignKey(db_column='id_detalle_egreso', on_delete=django.db.models.deletion.CASCADE, to='produccion.detalleegreso')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EGRESO',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_insumo', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('insumo_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.insumo')),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='DetalleTraspaso',
            fields=[
                ('id_detalle_traspaso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_insumo', models.IntegerField(blank=True, null=True)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('id_insumo', models.ForeignKey(blank=True, db_column='id_insumo', null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.insumo')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.producto')),
            ],
            options={
                'db_table': 'DETALLE_TRASPASO',
            },
        ),
        migrations.AddField(
            model_name='detalleegreso',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='produccion.producto'),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='produccion.categoria')),
            ],
            options={
                'db_table': 'SUBCATEGORIA',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_subcategoria',
            field=models.ForeignKey(db_column='id_subcategoria', on_delete=django.db.models.deletion.CASCADE, to='produccion.subcategoria'),
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id_traspaso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('id_detalle_traspaso', models.ForeignKey(db_column='id_detalle_traspaso', on_delete=django.db.models.deletion.CASCADE, to='produccion.detalletraspaso')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TRASPASO',
            },
        ),
    ]
