# Generated by Django 5.0.9 on 2024-12-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=20, null=True)),
            ],
            options={
                'db_table': 'COMPRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id_deposito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_deposito', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'DEPOSITO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'DETALLE_COMPRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaRecepcion',
            fields=[
                ('id_ficha_recepcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'FICHA_RECEPCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'INSUMO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_lote', models.DateField()),
            ],
            options={
                'db_table': 'LOTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('direccion', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.insumo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.solicitudcompra')),
            ],
        ),
    ]
